 - hosts: 192.168.200.162

   gather_facts: False
   pre_tasks:
     - name: Install python for Ansible
       raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)
       register: output
       changed_when: output.stdout != ""
     - setup: # aka gather_facts


   tasks:
      - name: fix hosts file
        blockinfile:
          name: /etc/hosts
          block: |
            192.168.100.2   Eros.infocom.pmr        Eros
            192.168.100.3   Ceres.infocom.pmr       Ceres
            192.168.100.4   Phoebe.infocom.pmr      Phoebe
            192.168.100.5   Ganymede.infocom.pmr    Ganymede            
            192.168.200.112 rocinante.infocom.pmr rocinante
            
      - name: fix sshd
        blockinfile:
          name: /etc/ssh/sshd_config
          block: |
            Port 22
            
      - name: fix slist
        lineinfile:
          name: /etc/apt/sources.list
          regexp: '^deb cdrom'
          line: '# deb cdrom:[Debian GNU/Linux 9.4.0 _Stretch_ - Official amd64 xfce-CD Binary-1 20180310-11:21]/ stretch main'
          backrefs: yes

      - name: test
        shell: >
          lsb_release -sc
        register: release

      - debug: var=release.stdout
 
      - name: download percona
        get_url:
          url: https://repo.percona.com/apt/percona-release_latest.{{release.stdout}}_all.deb
          dest: /

      - name: install repo percona
        apt: deb="/percona-release_latest.bionic_all.deb"


      - name: update cache + install percona
        apt:
          name: percona-xtradb-cluster-57
          update_cache: yes

      - name: remove apparmor
        apt:
          name: apparmor
          state: absent

      - name: mySQL stop
        service:
          name: mysql
          state: stopped
        
      - debug: var=ansible_default_ipv4.address
                  
      - debug: var=ansible_hostname

      - name: fix wsrep
        copy:
          dest: "/etc/mysql/percona-xtradb-cluster.conf.d/wsrep.cnf"
          content: |
            [mysqld]
            wsrep_provider=/usr/lib/galera3/libgalera_smm.so
            wsrep_cluster_address=gcomm://192.168.200.161,192.168.200.162,192.168.200.163,192.168.200.164
            binlog_format=ROW
            default_storage_engine=InnoDB
            wsrep_slave_threads= 8
            wsrep_log_conflicts
            innodb_autoinc_lock_mode=2
            wsrep_node_address={{ansible_default_ipv4.address}}
            wsrep_cluster_name=bm-cluster
            wsrep_node_name={{ansible_hostname}}
            pxc_strict_mode=ENFORCING
            wsrep_sst_method=xtrabackup-v2
            wsrep_sst_auth="sstuser:PASSWORD"

      
