- hosts: 192.168.200.162
  tasks:  
  - name: download percona
    get_url: 
      url: https://repo.percona.com/apt/percona-release_latest.stretch_all.deb
      dest: /

  - name: install pkg
    apt: deb="/percona-release_latest.stretch_all.deb"
      
  - name: install perconaDB
    apt: 
      name: percona-xtradb-cluster-57
      update_cache: yes

  - name: stop service on host_group
    service:
      name: mysql
      state: stopped

  - name: mysql conf
    lineinfile:
      name: /etc/mysql/percona-xtradb-cluster.conf.d/wsrep.cnf
      regexp: '^wsrep_cluster_address=gcomm://'
      line: 'wsrep_cluster_address=gcomm://192.168.200.161,192.168.200.162,192.168.200.163,192.168.200.164'
      backrefs: yes

