- hosts: debiancluster

  remote_user: root
  
  vars:
    password: $6$bffoCRSShO2C$bcBnEWhNecxdnVLzcBKxUg8QlmIUQ6EX7SLA5FMyXUafg5lRQjWn8NO8a/Oi53rmJ57I5zxOdZy9Fz9LWtGjv0

  tasks:

     - name: Install software
       apt: pkg={{ item }} state=installed update_cache=true
       with_items:
         - mc
         - nano
         - git
         - ntp
         - ntpdate
         - ntp-doc
         - python
         - python-pip
         - parted
         - xfsprogs
         - sudo

     - name: create cephuser group
       group: name=cephuser
       become: true

     - name: create cephuser
       user: name=cephuser password={{password}} group=cephuser shell=/bin/bash

     - name: shell tee
       shell: >
         echo "cephuser ALL = (root) NOPASSWD:ALL" |
         sudo tee /etc/sudoers.d/cephuser
         chmod 0440 /etc/sudoers.d/cephuser

     - name: chmod
       file:
         name: /etc/sudoers.d/cephuser
         mode: u=r,g=r,o-rwx

     - name: shell sed
       lineinfile:
         name: /etc/sudoers
         regexp: '^(Defaults\s,requiretty)$'
         line: '# \1'
         backrefs: yes
